# Generated by Django 5.1.1 on 2024-09-20 20:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Massage',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Идентификатор записи')),
                ('name', models.CharField(default=None, max_length=100, null=True)),
            ],
        ),
    ]
